### ISSUE TITLE
claimed gas failed with Neo wallet version 0.2.3

### ISSUE THREAD

**Issue by oanhschenk** [oanhschenk/my-puppy#1]
It has been 2 days using my Neo wallet version 0.2.3 to claim my claimable gas. But I always got the error message " claimable gas failed". Please help me to solve this issue!

**Comment by Cowboyup77** [comment]
I am having the same problem to let me know if you find anything out..

**Comment by oanhschenk** [comment]
Thank you very much! my wallet works now. I just claimed my gas . Have a great week!
